### ISSUE TITLE
Awesome work!

### ISSUE THREAD

**Issue by the-cashman** [azlee91/gtav-fivem-server#1]
Wanted to say thanks so much for putting this up here! I got gta5 from the free epic store promo and was looking to setup a server to play with a few friends and figuring everything out from scratch seemed like a pain for something casual. All the other docker images I found were pretty outdated and yours is also setup to support adding more resources! Awesome!

Thanks again, just letting you know ppl appreciate the hard work!

I don't have any issues to report yet haha but I will post when I do :).

**Comment by the-cashman** [comment]
Also lots of readmes and documentation, so great!

**Comment by azlee91** [comment]
Thank you so much! I appreciate it. Have fun!
